// Generated by gencpp from file prog_pkg/Deliver.msg
// DO NOT EDIT!


#ifndef PROG_PKG_MESSAGE_DELIVER_H
#define PROG_PKG_MESSAGE_DELIVER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prog_pkg
{
template <class ContainerAllocator>
struct Deliver_
{
  typedef Deliver_<ContainerAllocator> Type;

  Deliver_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  Deliver_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::prog_pkg::Deliver_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prog_pkg::Deliver_<ContainerAllocator> const> ConstPtr;

}; // struct Deliver_

typedef ::prog_pkg::Deliver_<std::allocator<void> > Deliver;

typedef boost::shared_ptr< ::prog_pkg::Deliver > DeliverPtr;
typedef boost::shared_ptr< ::prog_pkg::Deliver const> DeliverConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prog_pkg::Deliver_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prog_pkg::Deliver_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prog_pkg::Deliver_<ContainerAllocator1> & lhs, const ::prog_pkg::Deliver_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prog_pkg::Deliver_<ContainerAllocator1> & lhs, const ::prog_pkg::Deliver_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prog_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::prog_pkg::Deliver_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prog_pkg::Deliver_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prog_pkg::Deliver_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prog_pkg::Deliver_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prog_pkg::Deliver_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prog_pkg::Deliver_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prog_pkg::Deliver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::prog_pkg::Deliver_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa130bc60ee651385ULL;
  static const uint64_t static_value2 = 0x5dc62ea83fcc5b20ULL;
};

template<class ContainerAllocator>
struct DataType< ::prog_pkg::Deliver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prog_pkg/Deliver";
  }

  static const char* value(const ::prog_pkg::Deliver_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prog_pkg::Deliver_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 theta\n"
;
  }

  static const char* value(const ::prog_pkg::Deliver_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prog_pkg::Deliver_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Deliver_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prog_pkg::Deliver_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prog_pkg::Deliver_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROG_PKG_MESSAGE_DELIVER_H
