// Generated by gencpp from file prog_pkg/IsLoadedResponse.msg
// DO NOT EDIT!


#ifndef PROG_PKG_MESSAGE_ISLOADEDRESPONSE_H
#define PROG_PKG_MESSAGE_ISLOADEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prog_pkg
{
template <class ContainerAllocator>
struct IsLoadedResponse_
{
  typedef IsLoadedResponse_<ContainerAllocator> Type;

  IsLoadedResponse_()
    : result(0)  {
    }
  IsLoadedResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IsLoadedResponse_

typedef ::prog_pkg::IsLoadedResponse_<std::allocator<void> > IsLoadedResponse;

typedef boost::shared_ptr< ::prog_pkg::IsLoadedResponse > IsLoadedResponsePtr;
typedef boost::shared_ptr< ::prog_pkg::IsLoadedResponse const> IsLoadedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prog_pkg::IsLoadedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prog_pkg::IsLoadedResponse_<ContainerAllocator1> & lhs, const ::prog_pkg::IsLoadedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prog_pkg::IsLoadedResponse_<ContainerAllocator1> & lhs, const ::prog_pkg::IsLoadedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prog_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::prog_pkg::IsLoadedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prog_pkg/IsLoadedResponse";
  }

  static const char* value(const ::prog_pkg::IsLoadedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n"
;
  }

  static const char* value(const ::prog_pkg::IsLoadedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IsLoadedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prog_pkg::IsLoadedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prog_pkg::IsLoadedResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROG_PKG_MESSAGE_ISLOADEDRESPONSE_H
