// Generated by gencpp from file prog_pkg/IsLoaded.msg
// DO NOT EDIT!


#ifndef PROG_PKG_MESSAGE_ISLOADED_H
#define PROG_PKG_MESSAGE_ISLOADED_H

#include <ros/service_traits.h>


#include <prog_pkg/IsLoadedRequest.h>
#include <prog_pkg/IsLoadedResponse.h>


namespace prog_pkg
{

struct IsLoaded
{

typedef IsLoadedRequest Request;
typedef IsLoadedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IsLoaded
} // namespace prog_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prog_pkg::IsLoaded > {
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::prog_pkg::IsLoaded&) { return value(); }
};

template<>
struct DataType< ::prog_pkg::IsLoaded > {
  static const char* value()
  {
    return "prog_pkg/IsLoaded";
  }

  static const char* value(const ::prog_pkg::IsLoaded&) { return value(); }
};


// service_traits::MD5Sum< ::prog_pkg::IsLoadedRequest> should match
// service_traits::MD5Sum< ::prog_pkg::IsLoaded >
template<>
struct MD5Sum< ::prog_pkg::IsLoadedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prog_pkg::IsLoaded >::value();
  }
  static const char* value(const ::prog_pkg::IsLoadedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prog_pkg::IsLoadedRequest> should match
// service_traits::DataType< ::prog_pkg::IsLoaded >
template<>
struct DataType< ::prog_pkg::IsLoadedRequest>
{
  static const char* value()
  {
    return DataType< ::prog_pkg::IsLoaded >::value();
  }
  static const char* value(const ::prog_pkg::IsLoadedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prog_pkg::IsLoadedResponse> should match
// service_traits::MD5Sum< ::prog_pkg::IsLoaded >
template<>
struct MD5Sum< ::prog_pkg::IsLoadedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prog_pkg::IsLoaded >::value();
  }
  static const char* value(const ::prog_pkg::IsLoadedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prog_pkg::IsLoadedResponse> should match
// service_traits::DataType< ::prog_pkg::IsLoaded >
template<>
struct DataType< ::prog_pkg::IsLoadedResponse>
{
  static const char* value()
  {
    return DataType< ::prog_pkg::IsLoaded >::value();
  }
  static const char* value(const ::prog_pkg::IsLoadedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROG_PKG_MESSAGE_ISLOADED_H
